# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from MainWindow import FileManager


class Ui_Form(object):
    FileManager = FileManager()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(415, 247)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 40, 111, 16))

        font = QtGui.QFont()
        font.setPointSize(12)
        
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 111, 16))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 131, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 131, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)

        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        self.TitleEdit = QtWidgets.QLineEdit(Form)
        self.TitleEdit.setGeometry(QtCore.QRect(160, 30, 221, 31))
        self.TitleEdit.setText("")
        self.TitleEdit.setObjectName("TitleEdit")
        
        self.AuthorEdit = QtWidgets.QLineEdit(Form)
        self.AuthorEdit.setGeometry(QtCore.QRect(160, 70, 221, 31))
        self.AuthorEdit.setObjectName("AuthorEdit")
        
        self.YearEdit = QtWidgets.QLineEdit(Form)
        self.YearEdit.setGeometry(QtCore.QRect(160, 110, 221, 31))
        self.YearEdit.setObjectName("YearEdit")
        
        self.PageEdit = QtWidgets.QLineEdit(Form)
        self.PageEdit.setGeometry(QtCore.QRect(160, 150, 221, 31))
        self.PageEdit.setObjectName("PageEdit")
        
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(290, 200, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(lambda:self.AddButtonFunction(Form))


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def AddButtonFunction(self,Form): # Eklemeler burada gerceklesiyor
        self.FileManager.append_to_file( f"{self.TitleEdit.text()},{self.AuthorEdit.text()},{self.YearEdit.text()},{self.PageEdit.text()}\n")
        Form.hide()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Title"))
        self.label_2.setText(_translate("Form", "Author"))
        self.label_3.setText(_translate("Form", "Release year"))
        self.label_4.setText(_translate("Form", "Page"))
        self.pushButton.setText(_translate("Form", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
